[package]
name = "whispering"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.98"
cpal = "0.15.3"
dirs = "6.0.0"
hf-hub = { version = "0.4.2", features = ["tokio"] }
hound = "3.5.1"
log = "0.4.27"
rdev = { path = "../rdev", features =["wayland"] }
reqwest = { version = "0.12.15", features = ["json", "multipart", "stream"] }
samplerate = "0.2.4"
tokio = { version = "1.44.2", features = ["full"] }
whisper-rs = { path = "../whisper-rs", features = ["cuda"] }


[features]
jack = ["cpal/jack"]

