# Whispering Configuration Example
#
# Copy this file to ~/.config/whispering/config.toml and modify the values as needed.
# If no config.toml is found, the application will use default values.

[audio]
# Number of audio channels (1 for mono, 2 for stereo)
channels = 1
# Sample rate in Hz
sample_rate = 16000
# Bits per sample
bits_per_sample = 32
# Sample format (float or int)
sample_format = "float"

[model]
# Hugging Face model repository
repo = "ggerganov/whisper.cpp"
# Model filename
filename = "ggml-base.en.bin"

[paths]
# Cache directory for storing temporary files
cache_dir = "~/.cache/whispering"
# Path to the recorded audio file
recording_path = "~/.cache/whispering/recorded.wav"

[shortcuts]
# Keys that need to be pressed in sequence to start recording
# Available keys: control, alt, shift, super, space, enter, r, and many others
keys = ["ControlLeft", "Space"] 
# Automatically hit enter after sending the text (so sends a message in usual contexts).
autosend = false
